### ISSUE TITLE
Issue with creating ODBC DSN on Windows

### ISSUE THREAD

**Issue by AvirupDas** [mongodb/mongo-odbc-driver#5]
The application ODBC DSN freeze on creating the MongoDB DSN. Have not noticed any CPU or Memory spikes either for the same.
![odbcerror](https://user-images.githubusercontent.com/11179180/48885793-9554f480-ee4f-11e8-9141-a0bedb0634be.png)

**Comment by paulostradioti** [comment]
Same here.

**Comment by deafgoat** [comment]
@AvirupDas it looks like you're connecting to the MongoDB default port - 27017 - not the BI Connector default port - 3307.

Do you have the BI Connector running on port 27017?

**Comment by deafgoat** [comment]
In that case, please share the following so we can look into it further:

mongosqld (BIC) startup configuration and logs
mongod startup configuration and logs

**Comment by alikadir** [comment]
@AvirupDas the solution, 
you need to install [MongoDB Connector for BI](https://docs.mongodb.com/bi-connector/current/installation/) and then run [mongosqld.exe](https://docs.mongodb.com/bi-connector/current/launch/)
after try again connect ODBC 

![Capture](https://user-images.githubusercontent.com/11225437/54355643-aa59cb80-466a-11e9-9c86-02437c6173b4.JPG)
mongosqld.exe's default configuration localhost:3307

**Comment by tinesoft** [comment]
@alikadir  is right. 
What you need to configure in ODBC **is NOT the connection to your MongoDB Server** (running on <your_mongo_server_ip>:27017) , but instead, the connection to the **mongosqld** running on your machine (at localhost:3307 by default).

You must start the **mongosqld.exe** with a configuration file **instructing it how to connect to your MongoDB Server**:

**config_file.yml**
```
systemLog:
  logAppend: false
  path: "/path/to/mongosqld.log"
  verbosity: 2

security:
  enabled: true

mongodb:
  net:
    uri: "<your_mongo_server_ip>:27017"
    auth:
      source: "yourauthtication b"
      username: "<your_mongo_server_user>"
      password: "<your_mongo_server_password>"

net:
  bindIp: localhost
  port: 3307

schema:
  sample:
    namespaces: "<your_target_db_on_mongo.*"
```

To launch:
`$ mongosqld.exe --config=/path/to/config_file.yml`

_Beware that above config file must be **valid YAML** (no tabs, indentation with **2 spaces**) or else you'll get parsing issues when starting the mongosqld.exe_


Voilà!
